name: Build static pages

on:
  push:
    branches:
      - main
    paths:
      - data/stations.json
      - .github/workflows/build.yml
      - assets/script/station.mjs
      - templates/station.ejs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: node assets/script/station.mjs

      - name: Deploy static pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./stations
          external_repository: Mobifer/stations
          publish_branch: gh-pages
